### ISSUE TITLE
HTTPS?

### ISSUE THREAD

**Issue by leon332157** [chubin/pyphoon#13]
Could you please use Let's Encrypt for ssl cert?

**Comment by chubin** [comment]
you want this feature for wttr.in, not for pyphoon, because pyphoon is not a service.

It will be done soon: https://github.com/chubin/wttr.in/issues/16

**Comment by leon332157** [comment]
@chubin I'm Sorry.

**Comment by chubin** [comment]
@leon332157 Not a Problem! And I am sorry, that wttr.in still uses self-signed certificates. Shame on me. I promise, I'll fix it soon
