### ISSUE TITLE
How can I install and run pyphoon?

### ISSUE THREAD

**Issue by GittyMejorado** [chubin/pyphoon#27]
I am a beginner and I would like to be told the exact steps to install these scripts.
Thank you

**Comment by chubin** [comment]
Just check it out, and start it directly:
```
git clone https://github.com/chubin/pyphoon
bin/pyphoon
```

You can copy the script somewhere (with `lib/`),
and start it from that location

**Comment by martinbra** [comment]
For windows (probably linux too), assuming that python is in your PATH environment variable,  you can also:
```
>git clone https://github.com/chubin/pyphoon
>(cd to folder)
>python setup.py install
>pyphoon
```

**Comment by martinbra** [comment]
For Windows:
```
>git clone https://github.com/chubin/pyphoon
>cd pyphon
>python setup.py install (or python3 setup.py install)
>pyphoon
```

For Linux:
```
>git clone https://github.com/chubin/pyphoon
>cd pyphon
>sudo python3 setup.py install
>pyphoon
```

before `python setup.py install` it may be needed to install the requirements with
```
>pip install -r requirements.txt
```
or for conda:
```
>conda install pip
>pip install -r requirements.txt
```

**Comment by chubin** [comment]
I think we should add a small installation section to README, and then we can close this.
I believe this issue was created back in the time when installation using pip was not supported,
and so the installation procedure was not obvious, but even now a short installation instruction in README.md will do no harm

**Comment by martinbra** [comment]
Ok, I will add it before finishing the PR.

**Comment by chubin** [comment]
I think this can be closed now. Thank you, Martin, for extending the documentation
