### ISSUE TITLE
Missing hemisphere translations

### ISSUE THREAD

**Issue by martinbra** [chubin/pyphoon#32]
We are missing translations of North/South Hemisphere for:
bg, ca, cs, da, et, el, es, fi, hr, ia, it, ja, nl, pl, ro, sk and sr.

**Comment by chubin** [comment]
I have an idea where we can find these translations (as well as many additional ones):

```
curl -ks https://www.wikidata.org/wiki/Q41228 | grep 'hreflang=".." title=' | sed s@.*'hreflang="\(..\)" title=@\1 @; s@">.*@"@'
curl -ks https://www.wikidata.org/wiki/Q39061 | grep 'hreflang=".." title=' | sed s@.*'hreflang="\(..\)" title=@\1 @; s@">.*@"@'
```

We could easily add these translations to our dictionary

**Comment by martinbra** [comment]
Nice finding and sed magic there...
Too bad wiki data doesn't have the phases of the moon cataloged in the same way...

I will, by now, update the languages which we already have in the LITS dictionary.
