### ISSUE TITLE
I did translation for Armenian

### ISSUE THREAD

**Issue by Bombastik19** [chubin/pyphoon#40]
# This is translation for **_Armenian_** 
## English
'en': ["New Moon", "First Quarter", "Full Moon", "Last Quarter", "Northern Hemisphere", "Southern Hemisphere"],

## Armenian
'am': ["Նորալուսին", "Առաջին քառորդ", "Լիալուսին", "Վերջին քառորդ", "Հյուսիսային կիսագունդ", "Հարավային կիսագունդ"],

_sorry i don't know how to pull)_

**Comment by chubin** [comment]
Thank you very much for the translation. I've added and deployed it:

https://hy.wttr.in/moon

it is `hy` (ISO 639-1) not `am`; `am` is the country code.
